import numpy as np
import time
start = time.time()
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
col = np.random.rand(10000)
a = np.sqrt(np.sum(np.square(col - 10)))
print(time.time() - start)

